### ISSUE TITLE
How to update the live kernel

### ISSUE THREAD

**Issue by paolodongilli** [unixabg/remaster-iso#3]
I know this is not really an issue of remaster-iso but a request for help. I remastered a Debian "buster" iso without problems: Packages in the squashfs were updated, customizations were made, kernel 5.x was updated taking it from buster-backports.
A question though: **how can I also upgrade in a clean way the kernel of the live part of the iso**?
Thanks in advance for any hint.

**Comment by unixabg** [comment]
Greetings,

So kernel is a little messy, I have done it before. The general instructions as I can recall are something like:

1. extract as normal
2. edit as you describe with remaster-squashfs-editor
  2a. Save as a psu
3. Smash back to single squashfs
4. Launch  remaster-squashfs-editor
  4a. In an another terminal look for the new kernel in the iso-extract/live/psu_overlay. In there should be the latest kernel. Now copy kernel related files and name them appropriately to the iso-extract/live folder. fwiw: I always rename the old ones for sanity and leave them in the iso-extract/live folder just in case I need to go back or something. 
5. Compose image back together.
6. Test boot and see what kernel you get.
Hope this helps and if doesn't work let me know and I setup pristine and get exact info for you.

**Comment by paolodongilli** [comment]
Thank you for your explanation @unixabg . When you write "_Now copy kernel related files and name them appropriately to the iso-extract/live folder_" do you suggest to rename the new kernel related files to the old filenames in live?  
If this is the case, wouldn't it be possible to keep the new filenames (e.g. initrd.img-5.10.0-0.bpo.3-amd64, System.map-5.10.0-0.bpo.3-amd64, vmlinuz-5.10.0-0.bpo.3-amd64), and modify ./iso-extract/boot/grub/grub.cfg accordingly launching grub-mkimage?

**Comment by unixabg** [comment]
Greetings,
On Debian, and as I recall, on the "_Now copy kernel related files and name them appropriately to the iso-extract/live folder_", I actually believe you need not rename anything. I just edited the iso-extract/isolinux/menu.cfg and did a find and replace kernel version with vim. I only tested live things not any install things. And I do not think I did anything with grub.cfg.

**Comment by paolodongilli** [comment]
Thanks so much. I just tested it and it works flawlessly.
