### ISSUE TITLE
Squashfs read errors on ISOs of more than 2 GB size 

### ISSUE THREAD

**Issue by subhaniminhas** [unixabg/remaster-iso#4]
Once remastering an ISO to the point where final ISO becomes larger than 2 GB, writing image on a USB drive results in squashfs read errors, and USB cannot boot into the live desktop. I have used multiple tools to burn the iso images including balena etcher, ventoy , usbdiskimager etc, but same result. ISOs are based on Debian 11. Also most frustrating is that once the same ISO is booted in a Virtualbox session, it boot up normally. I have changed USB and all but issue is persistent. Please help in resolving the issue.

**Comment by unixabg** [comment]
@subhaniminhas - thank you for the report. Could you share a link to the iso you are starting with for remastering? Also can you share the OS you are using (I am assuming Debian xx, but want to double check)?

**Comment by subhaniminhas** [comment]
OS is Debian 11, I am making a custom Debian 11 based distro, PakOS Linux. However latest version is being developed using your tool, but I am stuck at the 2 GB limit. I will try to upload a stable iso of less than 2 GB and then send you the link. And really grateful for reaching back. Thanks a lot.

**Comment by unixabg** [comment]
@subhaniminhas - also what arch is your dev machine and target iso?

**Comment by subhaniminhas** [comment]
Both are amd64. Kindly wait a few days and hopefully I will be able to upload a less than 2 GB ISO at https://sourceforge.net/projects/pakos/

Then you can remaster the iso, add some heavy packages to cross the 2 GB limit and see the issue. 
Again thanks for quick reply. 

Regards.

**Comment by unixabg** [comment]
@subhaniminhas - sounds good and in the mean time I am happy to examine a broken one if you like. Oh the link you shared has one that is over 2GB. I will try that one maybe tomorrow.

**Comment by subhaniminhas** [comment]
Sir, really grateful. Kindly remember that last ISO of PakOS is Debian 10 based. Also in there you may find my own humble little utility called "Remaster PakOS". Its a Zenity GUI based bash script, not as polished as yours, but gets the job done. I used it to remaster my original PakOS ISOs. Once that script started giving me errors , I searched  and found yours, which is really great, but gives same errors on Debian 11. 
Kind regards.

**Comment by subhaniminhas** [comment]
I have added the original ISO of size 1.6 GB, which boots just fine, an ISO of size 2.1 GB which gives squashfs reading errors while booting from USB and a text file which contains some warnings which i encountered once i packed the iso using remaster-iso tools. All additional packages were installed using remaster-iso. 
Link to all files is here: 
https://drive.google.com/drive/folders/1iiZSA4j6COa819VBoOpeI18M7VRc0KMY?usp=share_link
If you can kindly find time to verify the problem and suggest any solution, i will be grateful.

**Comment by unixabg** [comment]
@subhaniminhas - thank you for the information. I will take a look this week.

**Comment by unixabg** [comment]
@subhaniminhas - on the errors file I don't think that is anything. Next on my side I downloaded the two iso files. The larger one I do get the errors as well. So I tested the live-image-amd64.hybrid.iso image and it booted well from usb. Next I added added a single copy of a large file, https://cdimage.debian.org/cdimage/weekly-builds/amd64/iso-cd/debian-edu-testing-amd64-netinst.iso , to the image and I left the delta as a psu file. This gave me an image size of 2.3G Mar 27 13:05  202303271305-remaster-iso.iso. This image booted fine.

Next I tried with three copies of the large file I downloaded and again just added change as another psu file (hence not remastering to single filesystem.squashfs). This gave me an image size of 3.0G Mar 27 13:25  202303271325-remaster-iso.iso.  This image booted fine.

The last thing I tested was a remaster of the last image to a single monolithic filesystem.squashfs file. I also remove the iso-extract/live/psu-OOS folder after. Then I composed with the following size 2.5G Mar 27 15:44  202303271544-remaster-iso.iso. This image booted fine as well.
 
At this point I am suspect that it could be something being added to the image not related to size. Can you share what you are adding from what appearas to be a basic debian live image?

**Comment by subhaniminhas** [comment]
Dear sir, really grateful for all the pain you took for a bug, which I believe is a result of some mis configuration at my end only. Recently I came across ISOs with only 1.6 GB size and still with same errors. I will try to make an iSO of smallest possible size with errors and share, but I think the problem might be in the host Debian, maybe. 
Meanwhile , searching desperately, I came across Penguins Eggs, which have really shortened my build, test, deploy process making it a WYSIWYG thing.  Thanks again for all the effort at your end. 
B.t.w, it's not required, but I can make a small YAD dialogue for you for remaster-iso scripts.
Happy Coding

**Comment by unixabg** [comment]
@subhaniminhas - First glad I could help. Next I am always open to code submission. I like cli but I know a lot of people do not and want gui things. If you submit as a PR then I can examine and if it operates well I can at the least include code in a contrib folder.
